### ISSUE TITLE
great app! and 6 years past, is there any improve suggestions?

### ISSUE THREAD

**Issue by zfjoy520** [ivanvc/lunetas#1]
if I decide to use it to build micro services such as sms service provider, or log collector etc. 
is there any improve suggestions?
thanks!

**Comment by ivanvc** [comment]
Sorry for the late response, but I created this micro-framework, which played nice with Rails 3 metals. I don't find it that useful now that there are better solutions. And not even sure if it works in newer Ruby versions. Have you tried Sinatra?

**Comment by zfjoy520** [comment]
@ivanvc Thank you for your reply.

Yes, I tried my old apis and web pages with sinatra 2 years ago, Sinatra is the best choice in that moment.

But, 2 years later, now I face 5x - 20x  api requests, we had 2000 sms requests in a seconds, for example. 

So, I need to rewrite those apis in rack for better performance.

^_^
